settings:
  application:
    host: 0.0.0.0
    port: "8350"
    name: service
    mode: dev
    domain: localhost:8350
    ishttps: false
  database:
    dbType: postgres
    host: localhost
    port: 5436
    name: db
    username: postgres
    password: postgres
  external:
    gometrurl: http://localhost:8300
