version: "3.9"

services:
  db:
    container_name: service-db
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASS:-postgres}
      - POSTGRES_DB=${DB_NAME:-db}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
